version: '3.8'

services:
  my-web:
    image: serversideup/php:8.2-fpm-nginx
    ports:
      - "3334:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - SSL_MODE=off
    networks:
      - front
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
